server:
  port: 8080

spring:
  application:
    name: minesweeper
  datasource:
    url: jdbc:postgresql://localhost:5433/minesweeper
    username: minesweeper
    password: minesweeper
    driver-class-name: org.postgresql.Driver

  jackson:
    default-property-inclusion: non_null




